## Course Reccomendation System 

In [1]:
from __future__ import annotations # To prevent Subscript for class "list" will generate runtime exception; enclose type annotation in quotes
import seaborn as sns
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math
import scipy
from sklearn.preprocessing import MinMaxScaler
from Kmeans import * 
%matplotlib inline

In [2]:
random_state = 42

#### Applying Pre-processing steps on data: 


In [3]:
df=pd.read_excel('Course Recommendation System.xlsx')
df=df.drop(['ID','Start time','Completion time','Email','Name','Name(not mandatory)\n' ], axis=1).fillna(0.5)
df 

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  Machine Learning\n  \
0                      0.85       0.90           0.70                0.70   
1                      0.20       0.80           0.80                0.50   
2                      1.00       1.00           1.00                1.00   
3                      0.20       0.75           0.75                0.75   
4                      0.20       0.00           0.80                0.50   
..                      ...        ...            ...                 ...   
157                    0.50       0.70           0.60                0.50   
158                    0.00       0.70           0.70                0.00   
159                    0.40       0.90           0.80                0.70   
160                    0.20       0.40           0.70                0.70   
161                    0.90       0.40           0.40                0.70   

     Mathematics For Machine Learning\n  Visual Recognition\n  \
0                                  0.80                  0.50   
1                                  0.10                  0.20   
2                                  1.00                  0.80   
3                                  0.75                  0.75   
4                                  0.60                  0.40   
..                                  ...                   ...   
157                                0.30                  0.70   
158                                0.00                  0.00   
159                                0.40                  0.50   
160                                0.80                  0.50   
161                                0.90                  0.50   

     Natural Language Processing\n  Reinforcement Learning  ...  \
0                              0.5                     0.5  ...   
1                              0.5                     0.5  ...   
2                              0.9                     1.0  ...   
3                              0.5                     0.5  ...   
4                              0.4                     0.2  ...   
..                             ...                     ...  ...   
157                            0.5                     0.5  ...   
158                            0.5                     0.5  ...   
159                            0.4                     0.2  ...   
160                            0.5                     0.7  ...   
161                            0.5                     0.8  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          0.5                       0.5           0.5   
1                          0.5                       0.5           0.5   
2                          0.5                       0.5           0.5   
3                          0.5                       0.5           0.5   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
157                        0.5                       0.5           0.5   
158                        0.5                       0.5           0.5   
159                        0.5                       0.5   

In [4]:
def cluster_to_matrix(X_train,y_train,num_cluster):
    k=Kmeans(K=num_cluster,iter=150,p=2,random_state=random_state)
    y_pred=k.predict(np.array(X_train),choice=0)
    k.centroids=np.array(k.centroids, dtype='int')
    X_train2 = pd.concat([X_train,y_train,pd.DataFrame(y_pred,columns=["label"],dtype='int')],axis="columns")
    df_cluster_rep = X_train2.groupby(['label'], as_index=False).mean()
    df_cluster_rep.drop(labels="label",axis="columns",inplace=True)
    matrix = df_cluster_rep.to_numpy()
    return matrix,k 

Performing the task on dataset 

In [5]:
X = df[[df.columns[0],df.columns[1],df.columns[3],df.columns[4]]]
y = df.drop(labels=["Data Structures and Algorithms","Computer Architecture\n","Discrete Mathematics\n","Economics","Programming-2"],axis="columns")

In [6]:
X

Data Structures and Algorithms  Computer Architecture\n  Economics  \
0                              0.30                     0.85       0.90   
1                              0.70                     0.80       0.80   
2                              0.70                     0.00       1.00   
3                              0.65                     0.70       0.75   
4                              0.70                     0.60       0.00   
..                              ...                      ...        ...   
157                            0.00                     1.00       0.70   
158                            1.00                     0.00       0.70   
159                            0.60                     0.30       0.90   
160                            0.80                     0.60       0.40   
161                            0.40                     0.70       0.40   

     Programming-2  
0             0.70  
1             0.80  
2             1.00  
3             0.75  
4             0.80  
..             ...  
157           0.60  
158           0.70  
159           0.80  
160           0.70  
161           0.40  

[162 rows x 4 columns]

In [7]:
y

Machine Learning\n  Mathematics For Machine Learning\n  \
0                  0.70                                0.80   
1                  0.50                                0.10   
2                  1.00                                1.00   
3                  0.75                                0.75   
4                  0.50                                0.60   
..                  ...                                 ...   
157                0.50                                0.30   
158                0.00                                0.00   
159                0.70                                0.40   
160                0.70                                0.80   
161                0.70                                0.90   

     Visual Recognition\n  Natural Language Processing\n  \
0                    0.50                            0.5   
1                    0.20                            0.5   
2                    0.80                            0.9   
3                    0.75                            0.5   
4                    0.40                            0.4   
..                    ...                            ...   
157                  0.70                            0.5   
158                  0.00                            0.5   
159                  0.50                            0.4   
160                  0.50                            0.5   
161                  0.50                            0.5   

     Reinforcement Learning  Software Production Engineering\n  \
0                       0.5                                0.5   
1                       0.5                                0.5   
2                       1.0                                0.0   
3                       0.5                                0.3   
4                       0.2                                0.7   
..                      ...                                ...   
157                     0.5                                0.5   
158                     0.5                                0.5   
159                     0.2                                0.7   
160                     0.7                                0.4   
161                     0.8                                0.5   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
0                    0.5                   0.5                      0.5   
1                    0.8                   0.5                      0.5   
2                    0.6                   0.0                      0.0   
3                    0.2                   0.5                      0.6   
4                    0.2                   0.2                      0.5   
..                   ...                   ...                      ...   
157                  0.0                   0.5                      0.5   
158                  1.0                   1.0                      0.0   
159                  0.7                   0.7                      0.7   
160                  0.4                   0.5                      0.6   
161                  0.5                   0.5                      0.4   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
0                  0.5                        0.5                       0.5   
1                  0.5                        0.5                       0.5   
2                  0.0                        0.5                       0.5   
3                  0.5                        0.5                       0.5   
4                  0.3                        0.0                       0.0   
..                 ...                        ...                       ...   
157                0.5                        0.5                       0.5   
158                0.5                        0.5                       0.5   
159                0.8                        0.5                       0.5   
160                0.5                     

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.05, shuffle=True,random_state=random_state)

In [9]:
matrix,kmeans_model = cluster_to_matrix(X_train,y_train,4)

In [10]:
matrix

array([[0.78152778, 0.68527778, 0.56      , 0.87833333, 0.78736111,
        0.72180556, 0.64097222, 0.54222222, 0.58319444, 0.61597222,
        0.50069444, 0.59791667, 0.62222222, 0.59166667, 0.38638889,
        0.36972222, 0.34916667, 0.38263889, 0.35138889, 0.40208333,
        0.42472222, 0.45597222, 0.45625   , 0.46666667],
       [0.81349663, 0.65641026, 0.58775714, 0.85020199, 0.78750135,
        0.68032265, 0.55365596, 0.51868048, 0.52442443, 0.65384615,
        0.49035547, 0.55134828, 0.48974359, 0.50162887, 0.36410256,
        0.38461538, 0.35641026, 0.34615385, 0.34358974, 0.45641026,
        0.5667093 , 0.50769231, 0.48205128, 0.59487179],
       [0.85      , 0.71875   , 0.7       , 0.790625  , 0.65625   ,
        0.546875  , 0.521875  , 0.5625    , 0.58125   , 0.55      ,
        0.35625   , 0.575     , 0.50625   , 0.625     , 0.375     ,
        0.375     , 0.3625    , 0.3625    , 0.375     , 0.425     ,
        0.525     , 0.54375   , 0.49375   , 0.59375   ],
       [0.833

In [11]:
matrix.shape

(4, 24)

In [12]:
from SVD import * 
u,s,sigma,V_trans = SVD(matrix)

[[7.729926   7.60778607 7.50370573 7.57600193]
 [7.60778607 7.57683567 7.4571036  7.52236762]
 [7.50370573 7.4571036  7.45041992 7.42679514]
 [7.57600193 7.52236762 7.42679514 7.67068549]]
[30.15526937  0.1496614   0.0855386   0.03739772]


In [13]:
matrix_clean = u@sigma@V_trans
matrix_clean = matrix_clean.astype('float')
matrix_clean

array([[0.78152778, 0.68527778, 0.56      , 0.87833333, 0.78736111,
        0.72180556, 0.64097222, 0.54222222, 0.58319444, 0.61597222,
        0.50069444, 0.59791667, 0.62222222, 0.59166667, 0.38638889,
        0.36972222, 0.34916667, 0.38263889, 0.35138889, 0.40208333,
        0.42472222, 0.45597222, 0.45625   , 0.46666667],
       [0.81349663, 0.65641026, 0.58775714, 0.85020199, 0.78750135,
        0.68032265, 0.55365596, 0.51868048, 0.52442443, 0.65384615,
        0.49035547, 0.55134828, 0.48974359, 0.50162887, 0.36410256,
        0.38461538, 0.35641026, 0.34615385, 0.34358974, 0.45641026,
        0.5667093 , 0.50769231, 0.48205128, 0.59487179],
       [0.85      , 0.71875   , 0.7       , 0.790625  , 0.65625   ,
        0.546875  , 0.521875  , 0.5625    , 0.58125   , 0.55      ,
        0.35625   , 0.575     , 0.50625   , 0.625     , 0.375     ,
        0.375     , 0.3625    , 0.3625    , 0.375     , 0.425     ,
        0.525     , 0.54375   , 0.49375   , 0.59375   ],
       [0.833

In [14]:
def predict(datapoint,kmeans,matrix_clean):
    ''' 
        @input: Takes in a datapoint, kmeans object, and information matrix 
        @output: Returns: rating sorted with index for column name mapping
    '''
    y_pred = kmeans.predictPoint(datapoint)
    inferred_full = matrix_clean[y_pred]
    inferred = inferred_full[5:]
    sorted_ratings = []
    for idx,element in enumerate(inferred):
        sorted_ratings.append([element,idx+5])
    sorted_ratings.sort()
    sorted_ratings.reverse()
    return sorted_ratings 

In [15]:
X_test

Data Structures and Algorithms  Computer Architecture\n  Economics  \
158                             1.0                      0.0       0.70   
109                             1.0                      1.0       1.00   
131                             0.9                      0.7       0.85   
55                              1.0                      1.0       1.00   
94                              0.8                      0.3       0.40   
29                              1.0                      0.0       0.00   
101                             1.0                      0.8       0.30   
51                              1.0                      1.0       0.40   
100                             1.0                      1.0       1.00   

     Programming-2  
158            0.7  
109            0.5  
131            0.8  
55             1.0  
94             0.9  
29             0.0  
101            0.8  
51             1.0  
100            0.0

In [16]:
y_test

Machine Learning\n  Mathematics For Machine Learning\n  \
158                0.00                                 0.0   
109                0.75                                 0.8   
131                0.60                                 0.7   
55                 1.00                                 1.0   
94                 1.00                                 1.0   
29                 1.00                                 1.0   
101                1.00                                 1.0   
51                 1.00                                 1.0   
100                1.00                                 1.0   

     Visual Recognition\n  Natural Language Processing\n  \
158                   0.0                            0.5   
109                   0.5                            0.5   
131                   0.7                            0.5   
55                    1.0                            0.5   
94                    0.6                            0.8   
29                    0.0                            0.0   
101                   1.0                            0.5   
51                    1.0                            1.0   
100                   1.0                            0.0   

     Reinforcement Learning  Software Production Engineering\n  \
158                     0.5                                0.5   
109                     0.5                                1.0   
131                     0.6                                0.7   
55                      0.5                                1.0   
94                      1.0                                1.0   
29                      0.0                                1.0   
101                     0.5                                0.8   
51                      1.0                                0.5   
100                     0.0                                1.0   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
158                  1.0                   1.0                      0.0   
109                  0.5                   0.5                      0.5   
131                  0.7                   0.7                      0.8   
55                   0.0                   0.0                      0.0   
94                   0.2                   0.7                      0.5   
29                   0.0                   0.0                      0.0   
101                  0.3                   0.9                      0.8   
51                   0.7                   0.5                      1.0   
100                  0.0                   0.0                      0.0   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
158               0.50                        0.5                       0.5   
109               0.50                        0.5                       1.0   
131               0.75                        0.5                       0.5   
55                0.00                        0.0                       0.0   
94                0.60                        0.0                       0.0   
29                0.00                        0.0                       0.0   
101               0.90                        0.0                       0.0   
51                0.50                        0.5                       0.5   
100               0.00                        0.0                       0.0   

     ASIC design   VLSI Architecture Design\n  \
158           0.5                         0.5   
109           0.7                         0.5   
131           0.5                         0.5   
55            0.0                         0.0   
94            0.0                         0.0   
29            0.0                         0.0   
101           0.0                         0.0   
51            0.4                         0.2   
100           0.0                         0.0   

     High level synthesis and optimization of Digital Circuits   \
158         

### Functions for whole test series application 

In [17]:
def predict_for_dataset(X_test,kmeans_instance,matrix_clean):
    ''' Runs out inference and return predicted ratings of subjects 
        @input: X_test,kmeans object, clean_matrix after SVD
    '''
    X_test = X_test.to_numpy()
    y_pred = []
    for i in range(X_test.shape[0]):
        datapoint =X_test[i][:5]
        y_pred.append(predict(datapoint,kmeans_instance,matrix_clean))
    return np.array(y_pred)

In [18]:
y_pred = predict_for_dataset(X_test,kmeans_model,matrix_clean) 

In [19]:
y_pred.shape

(9, 19, 2)

In [20]:
def accuracy(y_pred,y_test):
    ''' Finds out % common subject in top 5 rated subjects (predicted and actual) 
        @input: predicted values and test dataset values 
        @output: accuracy value 
    '''
    y_test = y_test.to_numpy()
    sorted_ratings_actual = []
    for i in range(y_test.shape[0]):
        inferred = y_test[i]
        t = []
        for idx,element in enumerate(inferred):
            t.append([element,idx+5])
        t.sort()
        t.reverse()
        sorted_ratings_actual.append(np.array(t))
    sorted_ratings_actual = np.array(sorted_ratings_actual)
    
    total = 0 
    correct = 0 

    
    for i in range(len(sorted_ratings_actual)):
        total+=5
        temp = sorted_ratings_actual[i][:5]
        # if i ==1:
        #     print(temp)
        for j in range(5):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):correct+=1

    perecent_correct_for_datapoint = []

    for i in range(len(sorted_ratings_actual)):
        per_correct = 0 
        temp = sorted_ratings_actual[i][:5]
        # if i ==1:
        #     print(temp)
        for j in range(5):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):per_correct+=1
        perecent_correct_for_datapoint.append(per_correct/5)
    print("Total Entries received: ", len(sorted_ratings_actual)*5," Total Correct: ",correct)
    return 100*(correct/total),perecent_correct_for_datapoint,sorted_ratings_actual
        

In [21]:
overall_val,per_point_val,y_sorted_actual = accuracy(y_pred,y_test)

Total Entries received:  45  Total Correct:  19


In [22]:
overall_val

42.22222222222222

In [23]:
per_point_val

[0.4, 0.4, 0.4, 0.4, 0.6, 0.4, 0.6, 0.2, 0.4]

In [24]:
def display_subject(sorted_ratings,names):
    '''
        @input: sorted_ratings list 
        @output: Names of subject corresponding
    '''
    s=""
    for i in range(5):
        s+=names[int(sorted_ratings[i][1])]+"\n"
    return s 

In [25]:
print(display_subject(y_pred[1],df.columns))

Machine Learning

Mathematics For Machine Learning

Data Visualization

Reinforcement Learning
Computer Graphics




In [26]:
print(display_subject(y_sorted_actual[1],df.columns))

System design with FPGA 
Software Production Engineering

Mathematics For Machine Learning

Machine Learning

ASIC design 

